const ASSETS = [
  {
    id: "dev-console-pro",
    name: "Dev Console Pro",
    description: "Powerful in-game developer console for Unity.",
    longDescription: "Dev Console Pro is a fully-featured in-game developer console that lets you run commands, inspect logs, and debug your game at runtime — on any platform. Register custom commands with one attribute, filter logs by type, and toggle the console with a configurable hotkey.",
    price: "$20",
    tags: ["Tools", "Debug"],
    storeUrl: "https://assetstore.unity.com/packages/your-link-here",
    thumb: "img/DevConsolePro/DevConsoleProPreviewImage_0.png",
    screenshots: [
      "img/DevConsolePro/DevConsoleProCoverImage_4.png",
      "img/DevConsolePro/DevConsoleProCoverImage_5.png",
      "img/DevConsolePro/DevConsoleProCoverImage_6.png",
      "img/DevConsolePro/DevConsoleProCoverImage_7.png",
      "img/DevConsolePro/DevConsoleProCoverImage_1.png",
      "img/DevConsolePro/DevConsoleProCoverImage_2.png",
      "img/DevConsolePro/DevConsoleProCoverImage_3.png",
    ],
    features: [
      "Register commands with a single [ConsoleCommand] attribute",
      "Filters logs by Info, Warning, Error, and Exception",
      "Persistent command history with arrow-key navigation",
      "Configurable toggle hotkey and UI theme",
      "Works on PC, mobile, and console builds",
      "Stack trace viewer for exceptions",
      "Autocomplete for registered commands",
    ],
    version: "1.3.0",
    unity: "2020.3+",
    docsPage: "docs/dev-console-pro.html",
  },
  {
    id: "instant-localization",
    name: "Instant Localization",
    description: "CSV-based localization workflow with editor tooling, QA, and auto-translate pipeline.",
    longDescription: "Instant Localization is a lightweight, in-editor localization system for Unity. Define all your strings in a simple CSV file, run the built-in QA checker to catch missing keys, and ship with confidence. Includes an auto-translate pipeline powered by DeepL and Azure Translate.",
    price: "$25",
    // salePrice: "$0",
    tags: ["Translator", "Editor"],
    storeUrl: "https://assetstore.unity.com/packages/tools/utilities/instant-localization-345178",
    thumb: "img/InstantLocalization/InstantLocalizationPreviewImage_0.png",
    screenshots: [
      "https://www.youtube.com/watch?v=sOU9y1pgckE",
      "https://www.youtube.com/watch?v=QZA0iVRCPUQ",
      "img/InstantLocalization/InstantLocalizationCoverImage_1.png",
      "img/InstantLocalization/InstantLocalizationCoverImage_2.png"],
    features: [
      "CSV-based string management — edit in any spreadsheet app",
      "Custom Editor window with live preview",
      "Auto-translate pipeline via Google Translate API",
      "QA checker that flags missing or duplicate keys",
      "Runtime language switching with zero scene reload",
      "Supports pluralisation and string formatting",
      "Zero runtime dependencies",
    ],
    version: "1.2.3",
    unity: "2021.3+",
    docsPage: "docs/instant-localization.html",
  },
  /*{
    id: "scene-transition-kit",
    name: "Scene Transition Kit",
    description: "Smooth animated transitions between scenes with a simple one-line API.",
    longDescription: "Scene Transition Kit gives your game polished scene changes with zero boilerplate. Pick from 20+ built-in transitions — fade, wipe, iris, pixelate — or create your own with a custom shader. Trigger any transition with a single method call.",
    price: "$12",
    tags: ["UI", "Animation"],
    storeUrl: "https://assetstore.unity.com/packages/your-link-here",
    thumb: "img/placeholders/scene-transition-kit.png",
    features: [
      "20+ built-in transition effects",
      "One-line API: TransitionManager.LoadScene(\"Level2\", Transition.Fade)",
      "Custom shader support for fully unique transitions",
      "Async/await compatible loading",
      "Works with Additive and Single load modes",
      "Configurable duration and easing curves",
    ],
    version: "1.1.0",
    unity: "2021.3+",
  },
  {
    id: "save-system-pro",
    name: "Save System Pro",
    description: "JSON and binary save/load system with encryption, versioning, and cloud sync support.",
    longDescription: "Save System Pro handles all the hard parts of game persistence. Serialize any C# object to JSON or compact binary, encrypt the file with AES-256, and version your save format so old saves migrate cleanly after patches.",
    price: "$18",
    salePrice: "$12",
    tags: ["Tools", "Utilities"],
    storeUrl: "https://assetstore.unity.com/packages/your-link-here",
    thumb: "img/placeholders/save-system-pro.png",
    features: [
      "JSON and binary serialization backends",
      "AES-256 file encryption",
      "Save versioning with automatic migration callbacks",
      "Multiple save slots out of the box",
      "Cloud sync adapter interface (Steam, GameSave)",
      "Editor window to inspect and wipe save files",
    ],
    version: "2.0.1",
    unity: "2020.3+",
  },
  {
    id: "dialogue-engine",
    name: "Dialogue Engine",
    description: "Node-based dialogue system with branching, variables, and localization support.",
    longDescription: "Dialogue Engine lets you build rich branching conversations entirely in the Unity Editor. Connect nodes visually, bind variables from your game code, trigger events mid-dialogue, and pipe all strings through your localization system automatically.",
    price: "$30",
    tags: ["Editor", "Narrative"],
    storeUrl: "https://assetstore.unity.com/packages/your-link-here",
    thumb: "img/placeholders/dialogue-engine.png",
    features: [
      "Visual node graph editor",
      "Condition and branch nodes driven by game variables",
      "Event nodes that fire UnityEvents mid-conversation",
      "Built-in localization key mapping",
      "Import/export dialogues as JSON or YAML",
      "Runtime API: Next(), Choose(index), Skip()",
    ],
    version: "3.2.0",
    unity: "2021.3+",
  },
  {
    id: "inventory-framework",
    name: "Inventory Framework",
    description: "Flexible drag-and-drop inventory with item stacking, equipment slots, and serialization.",
    longDescription: "Inventory Framework gives you a production-ready item system you can drop into any genre. Define items with ScriptableObjects, build grids and equipment layouts with a drag-and-drop editor, and serialize the entire state with one call.",
    price: "$22",
    tags: ["UI", "Systems"],
    storeUrl: "https://assetstore.unity.com/packages/your-link-here",
    thumb: "img/placeholders/inventory-framework.png",
    features: [
      "Grid and slot inventory layouts",
      "Item stacking and max stack size rules",
      "Equipment slots with stat modifier hooks",
      "ScriptableObject item definitions",
      "Drag-and-drop between grids at runtime",
      "Full serialization / deserialization support",
    ],
    version: "1.4.2",
    unity: "2021.3+",
  },
  {
    id: "audio-manager",
    name: "Audio Manager",
    description: "Pooled audio manager with mixer integration, fade in/out, and playlist support.",
    longDescription: "Audio Manager wraps Unity's AudioSource with a clean pooled API so you never stutter from instantiation. Fade music tracks, queue playlists, and route everything through named AudioMixer groups — all from a single manager.",
    price: "$10",
    tags: ["Audio", "Tools"],
    storeUrl: "https://assetstore.unity.com/packages/your-link-here",
    thumb: "img/placeholders/audio-manager.png",
    features: [
      "Source pooling — zero instantiation at runtime",
      "Fade in / fade out with configurable curves",
      "Playlist queue with shuffle and loop modes",
      "AudioMixer group routing per sound",
      "3D spatial audio support",
      "Simple API: AudioManager.Play(\"explosion\")",
    ],
    version: "1.0.4",
    unity: "2020.3+",
  },
  {
    id: "object-pooler",
    name: "Object Pooler",
    description: "High-performance generic object pool with pre-warm, auto-expand, and editor preview.",
    longDescription: "Object Pooler is a zero-allocation pooling solution for any Unity GameObject. Pre-warm pools at startup, let them grow automatically when exhausted, and profile every pool live in a dedicated Editor window.",
    price: "$8",
    salePrice: "$5",
    tags: ["Performance", "Tools"],
    storeUrl: "https://assetstore.unity.com/packages/your-link-here",
    thumb: "img/placeholders/object-pooler.png",
    features: [
      "Generic pool — works with any GameObject prefab",
      "Pre-warm on Awake with configurable initial size",
      "Auto-expand when pool is exhausted",
      "Hard-cap mode to prevent unbounded growth",
      "Editor window shows live active / idle counts",
      "Zero allocations in steady-state gameplay",
    ],
    version: "1.2.0",
    unity: "2020.3+",
  },
  {
    id: "input-rebinder",
    name: "Input Rebinder",
    description: "Runtime key rebinding UI with Unity's new Input System. Supports gamepad and keyboard.",
    longDescription: "Input Rebinder wires straight into Unity's Input System and gives players a fully-functional rebinding panel at runtime. Detect conflicts, save bindings to PlayerPrefs, and reset to defaults — all built in.",
    price: "$15",
    tags: ["Input", "UI"],
    storeUrl: "https://assetstore.unity.com/packages/your-link-here",
    thumb: "img/placeholders/input-rebinder.png",
    features: [
      "Works with Unity Input System action maps",
      "Keyboard and gamepad rebinding in the same UI",
      "Conflict detection with user prompt",
      "Bindings persisted to PlayerPrefs automatically",
      "Reset-to-defaults button",
      "Fully styleable UGUI prefab included",
    ],
    version: "1.1.1",
    unity: "2021.3+",
  },
  {
    id: "minimap-system",
    name: "Minimap System",
    description: "Real-time render-texture minimap with icons, zoom, and fog-of-war mask.",
    longDescription: "Minimap System renders a live top-down view of your world onto a UI RawImage using a dedicated camera and RenderTexture. Add map icons for enemies, objectives, and players. Apply a fog-of-war mask that lifts as the player explores.",
    price: "$20",
    tags: ["UI", "2D"],
    storeUrl: "https://assetstore.unity.com/packages/your-link-here",
    thumb: "img/placeholders/minimap-system.png",
    features: [
      "RenderTexture-based — works in 2D and 3D",
      "Configurable minimap camera with zoom levels",
      "Icon system: any world object can register an icon",
      "Fog-of-war mask driven by player exploration",
      "Circular or rectangular minimap frame",
      "Rotation-locked or north-up modes",
    ],
    version: "2.1.0",
    unity: "2021.3+",
  },
  {
    id: "quest-manager",
    name: "Quest Manager",
    description: "Data-driven quest system with objectives, rewards, and runtime editor integration.",
    longDescription: "Quest Manager uses ScriptableObjects to define quests, objectives, and reward tables. Track progress at runtime, fire callbacks on completion, and inspect every active quest in the Editor play-mode window without a single line of debug code.",
    price: "$28",
    tags: ["Systems", "Editor"],
    storeUrl: "https://assetstore.unity.com/packages/your-link-here",
    thumb: "img/placeholders/quest-manager.png",
    features: [
      "ScriptableObject quest and objective definitions",
      "Multi-objective quests with sequential or parallel modes",
      "Reward tables with loot table support",
      "OnQuestStarted / OnObjectiveCompleted / OnQuestFinished events",
      "Play-mode editor window with live state",
      "Save/load quest state via JSON",
    ],
    version: "1.3.0",
    unity: "2021.3+",
  },
  {
    id: "shader-graph-pack",
    name: "Shader Graph Pack",
    description: "30+ ready-to-use URP shader graphs: dissolve, outline, hologram, water, and more.",
    longDescription: "Shader Graph Pack is a library of 30+ production-ready URP shaders built entirely in Shader Graph — fully editable, fully documented. Drop them into your project and tweak every parameter from the Material inspector.",
    price: "$35",
    salePrice: "$20",
    tags: ["Shaders", "URP"],
    storeUrl: "https://assetstore.unity.com/packages/your-link-here",
    thumb: "img/placeholders/shader-graph-pack.png",
    features: [
      "30+ shaders — dissolve, outline, hologram, water, lava, ice and more",
      "Built entirely in Shader Graph — no hidden HLSL",
      "Every parameter exposed in the Material inspector",
      "URP 12+ compatible",
      "Demo scene for every shader",
      "Detailed comments inside each graph",
    ],
    version: "1.0.0",
    unity: "2021.3+",
  },
  {
    id: "notification-system",
    name: "Notification System",
    description: "In-game toast notifications with queue, priority, icons, and animated slide-in.",
    longDescription: "Notification System gives your game professional toast notifications. Queue unlimited messages, assign priority levels, attach icons, and let the system animate them in and out automatically — no coroutines needed on your end.",
    price: "$10",
    tags: ["UI", "Tools"],
    storeUrl: "https://assetstore.unity.com/packages/your-link-here",
    thumb: "img/placeholders/notification-system.png",
    features: [
      "Queue with configurable max visible count",
      "Priority levels: Low, Normal, High, Critical",
      "Icon support per notification",
      "Slide-in / slide-out with custom animation curves",
      "4 built-in anchor positions (corners)",
      "One-line API: Notify.Show(\"Level Up!\", icon, Priority.High)",
    ],
    version: "1.1.0",
    unity: "2020.3+",
  },
  {
    id: "event-bus",
    name: "Event Bus",
    description: "Decoupled typed event bus for clean cross-system communication without singletons.",
    longDescription: "Event Bus replaces singleton-to-singleton calls with a clean publish/subscribe system. Define an event as a plain C# struct, publish it from anywhere, and subscribe from anywhere else — with zero hard references between systems.",
    price: "$8",
    tags: ["Architecture", "Tools"],
    storeUrl: "https://assetstore.unity.com/packages/your-link-here",
    thumb: "img/placeholders/event-bus.png",
    features: [
      "Fully generic: EventBus<T>.Publish(new MyEvent())",
      "Subscribe and unsubscribe with lambda or method reference",
      "No MonoBehaviour required — pure C#",
      "Automatic cleanup helpers for MonoBehaviour subscribers",
      "Editor window shows all registered listeners live",
      "Zero allocations for value-type events",
    ],
    version: "1.0.2",
    unity: "2020.3+",
  },
  {
    id: "state-machine-pro",
    name: "State Machine Pro",
    description: "Hierarchical state machine with visual debugger, transitions, and ScriptableObject states.",
    longDescription: "State Machine Pro brings structured, readable AI and gameplay logic to your project. Define states as ScriptableObjects, wire transitions with conditions in the Inspector, and watch the active state highlight in the visual debugger during play mode.",
    price: "$20",
    tags: ["AI", "Architecture"],
    storeUrl: "https://assetstore.unity.com/packages/your-link-here",
    thumb: "img/placeholders/state-machine-pro.png",
    features: [
      "Hierarchical states — substates inherit transitions",
      "ScriptableObject state definitions",
      "Condition-based transitions configured in the Inspector",
      "OnEnter / OnTick / OnExit callbacks",
      "Visual debugger highlights current state at runtime",
      "Supports both MonoBehaviour and pure C# owners",
    ],
    version: "2.0.0",
    unity: "2021.3+",
  },
  {
    id: "floating-damage-text",
    name: "Floating Damage Text",
    description: "Pooled world-space damage numbers with curves, color ramps, and crit animations.",
    longDescription: "Floating Damage Text spawns polished damage numbers from a pool so performance never dips during heavy combat. Drive colour and scale from AnimationCurves, register crit hits for a big-pop animation, and position labels automatically in world space.",
    price: "$9",
    tags: ["UI", "VFX"],
    storeUrl: "https://assetstore.unity.com/packages/your-link-here",
    thumb: "img/placeholders/floating-damage-text.png",
    features: [
      "Object-pooled — no allocation during combat",
      "AnimationCurve-driven scale and fade",
      "Color ramp: white → yellow → red by damage amount",
      "Crit hit variant with screen-shake and bounce",
      "World-space billboard — always faces camera",
      "Works with TextMeshPro",
    ],
    version: "1.0.1",
    unity: "2020.3+",
  },
  {
    id: "settings-manager",
    name: "Settings Manager",
    description: "Persistent player settings panel — graphics, audio, controls — with a clean default UI.",
    longDescription: "Settings Manager ships a complete settings screen you can drop into any project. Graphics quality, resolution, audio volumes, and control hints all backed by PlayerPrefs with a reactive UI that updates in real time as the player adjusts each slider or dropdown.",
    price: "$14",
    salePrice: "$9",
    tags: ["UI", "Utilities"],
    storeUrl: "https://assetstore.unity.com/packages/your-link-here",
    thumb: "img/placeholders/settings-manager.png",
    features: [
      "Graphics tab: quality, resolution, fullscreen, VSync",
      "Audio tab: master, music, SFX volume sliders",
      "Controls tab: keybinding display and reset",
      "All settings backed by PlayerPrefs automatically",
      "Reactive UI — applies changes instantly without restart",
      "Fully reskinnable UGUI prefab",
    ],
    version: "1.2.0",
    unity: "2021.3+",
  },*/
];